
package GUI;
import exceptions.InvalidAccountException;
import exceptions.OverdraftLimitExceededException;
import java.awt.event.ActionListener;
/**
 *
 * @author Yosef - 255796
 */
public class AccountPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountPanel.class.getName());

    static void addActionListener(ActionListener actionListener) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel() {
        initComponents();
        
        
       // Add this code - Next button functionality
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Get the selected account from combo box
            String selectedAccount = selecctComboBox.getSelectedItem().toString();
            
            // Check which account is selected and update the text fields
            if (selectedAccount.equals("Savings")) {
                interestrate.setText("5.0%");
                overdraft.setText("Not Available");
                benefits.setText("Earns interest + Min Balance: $100.00");
                
            } else if (selectedAccount.equals("Current")) {
                interestrate.setText("0.0%");
                overdraft.setText("$500.00");
                benefits.setText("Transaction Limit: 50/month + Yearly Fee: $25.00");
                
            } else if (selectedAccount.equals("Premium")) {
                interestrate.setText("5.0%");
                overdraft.setText("$10,000.00");
                benefits.setText("5% Bonus Rate + Yearly Fee: $75.00");
                
            } else {
                // If "Select" is chosen
                interestrate.setText("");
                overdraft.setText("");
                benefits.setText("");
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chooseAcccount = new javax.swing.JLabel();
        selecctComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        interestrate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        overdraft = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        benefits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Account Panel");
        jPanel1.add(jLabel9, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Next");
        jPanel2.add(jButton1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        chooseAcccount.setText("Choose Acccount");
        jPanel3.add(chooseAcccount);

        selecctComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Savings", "Current", "Premium" }));
        selecctComboBox.addActionListener(this::selecctComboBoxActionPerformed);
        jPanel3.add(selecctComboBox);

        jLabel1.setText(" interest rate");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1);

        interestrate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        interestrate.setEnabled(false);
        interestrate.addActionListener(this::interestrateActionPerformed);
        jPanel3.add(interestrate);

        jLabel2.setText(" overdraft");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2);

        overdraft.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        overdraft.setEnabled(false);
        overdraft.addActionListener(this::overdraftActionPerformed);
        jPanel3.add(overdraft);

        jLabel3.setText(" benefits");
        jPanel3.add(jLabel3);

        benefits.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        benefits.setEnabled(false);
        jPanel3.add(benefits);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interestrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestrateActionPerformed

    private void selecctComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecctComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecctComboBoxActionPerformed

    private void overdraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overdraftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overdraftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccountPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField benefits;
    private javax.swing.JLabel chooseAcccount;
    private javax.swing.JTextField interestrate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField overdraft;
    private javax.swing.JComboBox<String> selecctComboBox;
    // End of variables declaration//GEN-END:variables
}
