package Yousif_Hafez_gui;
    
import models.user.Client;
import models.user.CardStatus;
/**
 * Frame used to manage client card status
 * Allows issuing a card and updating its status (Active, Inactive, Lost, Stuck)
 *
 * @author Yousif Hafez - 258612
 */
public class CardForm extends javax.swing.JFrame {

    Client client;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardForm.class.getName());

    /**
     * Creates new form CardForm
     * @param client
     */
    public CardForm(Client client) {
    initComponents();
    this.client = client;
    setLocationRelativeTo(null);

    client.loadCardStatus();   
    refreshStatus();           
}

    private CardForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


/**
 * Updates the status label
 */
private void refreshStatus() {
    statusLabel.setText("Status: " + client.getCardStatus());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Cardmanagement = new javax.swing.JLabel();
        Active = new javax.swing.JRadioButton();
        Inactive = new javax.swing.JRadioButton();
        Lost = new javax.swing.JRadioButton();
        issueCard = new javax.swing.JButton();
        blockCard = new javax.swing.JButton();
        Stuck = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cardmanagement.setText("Card Management");

        buttonGroup1.add(Active);
        Active.setText("Active");
        Active.addActionListener(this::ActiveActionPerformed);

        buttonGroup1.add(Inactive);
        Inactive.setText("Inactive");
        Inactive.addActionListener(this::InactiveActionPerformed);

        buttonGroup1.add(Lost);
        Lost.setText("Lost");
        Lost.addActionListener(this::LostActionPerformed);

        issueCard.setText("Issue Card");
        issueCard.addActionListener(this::issueCardActionPerformed);

        blockCard.setText("Block Card");
        blockCard.addActionListener(this::blockCardActionPerformed);

        buttonGroup1.add(Stuck);
        Stuck.setText("Stuck");
        Stuck.addActionListener(this::StuckActionPerformed);

        statusLabel.setText("Status:Inactive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inactive, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lost, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cardmanagement)
                    .addComponent(Stuck, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(issueCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockCard))
                    .addComponent(Active, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Cardmanagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addGap(5, 5, 5)
                .addComponent(Inactive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Active)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stuck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueCard)
                    .addComponent(blockCard))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Sets card status to ACTIVE when the Active option is selected.
    * Updates the UI label to reflect the new status.
    */
    private void ActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveActionPerformed
    // Update card status to ACTIVE
    client.updateCardStatus(CardStatus.ACTIVE);

    // Show confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to ACTIVE");

    // Refresh status label
    refreshStatus();
    }//GEN-LAST:event_ActiveActionPerformed
       
 /**
 * Updates the card status based on the selected radio button.
 * Allows the user to set the card to ACTIVE, INACTIVE, LOST, or STUCK.
 */
    private void issueCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueCardActionPerformed
    if (Active.isSelected()) {
        // Set card status to ACTIVE
        client.updateCardStatus(CardStatus.ACTIVE);
    } 
    else if (Inactive.isSelected()) {
        // Set card status to INACTIVE
        client.updateCardStatus(CardStatus.INACTIVE);
    } 
    else if (Lost.isSelected()) {
        // Mark the card as LOST
        client.updateCardStatus(CardStatus.LOST);
    } 
    else if (Stuck.isSelected()) {
        // Mark the card as STUCK
        client.updateCardStatus(CardStatus.STUCK);
    } 
    else {
        // No option selected
        javax.swing.JOptionPane.showMessageDialog(this, "Select a status first");
        return;
    }
    // Confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card status updated successfully");
    // Update status label
    refreshStatus();
    }//GEN-LAST:event_issueCardActionPerformed

    
    /**
    * Sets card status to LOST when the Lost option is selected.
    * Used when the card is reported lost or stolen.
    */
    private void LostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LostActionPerformed

    // Update card status to LOST
    client.updateCardStatus(CardStatus.LOST);

    // Show confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to LOST");

    // Refresh status label
    refreshStatus();
    }//GEN-LAST:event_LostActionPerformed
    
    /**
    * Sets card status to STUCK when the Stuck option is selected.
    * Used when the card is retained by an ATM.
    */
     private void StuckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuckActionPerformed
        // Update card status to STUCK
    client.updateCardStatus(CardStatus.STUCK);

    // Show confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to STUCK");

    // Refresh status label
    refreshStatus();
    }//GEN-LAST:event_StuckActionPerformed
    
    /**
    * Blocks the client's card by setting its status to LOST.
    * Used when the card is reported lost or stolen.
    */
    private void blockCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockCardActionPerformed
    // Update card status to LOST (blocked)
    client.updateCardStatus(CardStatus.LOST);

    // Show confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card blocked (LOST)");

    // Refresh status label on UI
    refreshStatus();
    }//GEN-LAST:event_blockCardActionPerformed


    /**
    * Sets card status to INACTIVE when the Inactive option is selected.
    * Updates the UI label to reflect the new status.
    */
    private void InactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactiveActionPerformed
    // Update card status to INACTIVE
    client.updateCardStatus(CardStatus.INACTIVE);

    // Show confirmation message
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to INACTIVE");

    // Refresh status label
    refreshStatus();
    }//GEN-LAST:event_InactiveActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new CardForm().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Active;
    private javax.swing.JLabel Cardmanagement;
    private javax.swing.JRadioButton Inactive;
    private javax.swing.JRadioButton Lost;
    private javax.swing.JRadioButton Stuck;
    private javax.swing.JButton blockCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton issueCard;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
