package Yousif_Hafez_gui;

import exceptions.InsufficientFundsException;
import exceptions.InvalidAmountException;
import models.account.Account;

/**
 * Dialog used to perform account transactions
 * Allows user to deposit or withdraw money from an account
 *
 * @author Yousif Hafez - 258612
 */
public class TransactionDialog extends javax.swing.JFrame {
    
    /**
    * The account on which transactions will be performed
    */
    private Account account;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionDialog.class.getName());

    /**
     * Creates new form TransactionDialog
     */
    public TransactionDialog() {
        initComponents();
    }

    /**
    * Creates TransactionDialog linked to a specific account
    *
    * @param account the account used for deposit/withdraw
    */
    public TransactionDialog(Account account) {
    initComponents();
    this.account = account;
    setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountFiled = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        excuteButton = new javax.swing.JButton();
        amountField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amountFiled.setText("Amount:");

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw" }));
        typeBox.addActionListener(this::typeBoxActionPerformed);

        excuteButton.setText("Excute");
        excuteButton.addActionListener(this::excuteButtonActionPerformed);

        amountField.addActionListener(this::amountFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(amountFiled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(excuteButton))
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountFiled)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excuteButton)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeBoxActionPerformed

    /**
    * Handles Execute button click
    * Performs Deposit or Withdraw based on selected type
    */
    private void excuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excuteButtonActionPerformed
    try {
        // Read amount from text field
        double amount = Double.parseDouble(amountField.getText());

        // Validate amount
        if (amount <= 0) {
            throw new InvalidAmountException();
        }

        // Get selected transaction type
        String type = typeBox.getSelectedItem().toString();

        // Perform operation
        if (type.equals("Deposit")) {

            // Deposit money into account
            account.deposit(amount);

            // Show success message
            javax.swing.JOptionPane.showMessageDialog(this, "Deposit successful");

        } else {

            // Withdraw money from account
            account.withdraw(amount);

            // Show success message
            javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal successful");
        }

        // Clear input field after operation
        amountField.setText("");

    } catch (NumberFormatException e) {

        // Input is not a valid number
        javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid number");

    } catch (InvalidAmountException e) {

        // Amount is invalid (<= 0)
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());

    }
    }//GEN-LAST:event_excuteButtonActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountFiled;
    private javax.swing.JButton excuteButton;
    private javax.swing.JComboBox<String> typeBox;
    // End of variables declaration//GEN-END:variables
}
