package gui.customer;

import manager.BankSystem;
import models.user.Client;
import models.user.CardStatus;
/**
 * Frame used to manage client card status
 * Allows issuing a card and updating its status (Active, Inactive, Lost, Stuck)
 *
 * @author Yousif Hafez - 258612
 */
public class CardManagementFrame extends javax.swing.JFrame {

    Client client;
    BankSystem bank;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardManagementFrame.class.getName());

    public CardManagementFrame(Client client) {
        this(client, null);
    }

    public CardManagementFrame(Client client, BankSystem bank) {
        initComponents();
        this.client = client;
        this.bank = bank;
        setLocationRelativeTo(null);
        refreshStatus();
    }

    private CardManagementFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

/**
 * Updates the status label
 */
private void refreshStatus() {
    statusLabel.setText("Status: " + client.getCardStatus());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Cardmanagement = new javax.swing.JLabel();
        Active = new javax.swing.JRadioButton();
        Inactive = new javax.swing.JRadioButton();
        Lost = new javax.swing.JRadioButton();
        issueCard = new javax.swing.JButton();
        blockCard = new javax.swing.JButton();
        Stuck = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Cardmanagement.setText("Card Management");

        buttonGroup1.add(Active);
        Active.setText("Active");
        Active.addActionListener(this::ActiveActionPerformed);

        buttonGroup1.add(Inactive);
        Inactive.setText("Inactive");
        Inactive.addActionListener(this::InactiveActionPerformed);

        buttonGroup1.add(Lost);
        Lost.setText("Lost");
        Lost.addActionListener(this::LostActionPerformed);

        issueCard.setText("Issue Card");
        issueCard.addActionListener(this::issueCardActionPerformed);

        blockCard.setText("Block Card");
        blockCard.addActionListener(this::blockCardActionPerformed);

        buttonGroup1.add(Stuck);
        Stuck.setText("Stuck");
        Stuck.addActionListener(this::StuckActionPerformed);

        statusLabel.setText("Status:Inactive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inactive, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lost, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cardmanagement)
                    .addComponent(Stuck, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(issueCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockCard))
                    .addComponent(Active, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Cardmanagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addGap(5, 5, 5)
                .addComponent(Inactive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Active)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stuck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueCard)
                    .addComponent(blockCard))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }

    private void saveIfNeeded() {
        if (bank != null) {
            bank.saveAllData();
        }
    }

    /**
    * Sets card status to ACTIVE when the Active option is selected.
    * Updates the UI label to reflect the new status.
    */
    private void ActiveActionPerformed(java.awt.event.ActionEvent evt) {
    client.updateCardStatus(CardStatus.ACTIVE);
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to ACTIVE");
    refreshStatus();
    }

 /**
 * Updates the card status based on the selected radio button.
 * Allows the user to set the card to ACTIVE, INACTIVE, LOST, or STUCK.
 */
    private void issueCardActionPerformed(java.awt.event.ActionEvent evt) {
    if (Active.isSelected()) {
        client.updateCardStatus(CardStatus.ACTIVE);
    }
    else if (Inactive.isSelected()) {
        client.updateCardStatus(CardStatus.INACTIVE);
    }
    else if (Lost.isSelected()) {
        client.updateCardStatus(CardStatus.LOST);
    }
    else if (Stuck.isSelected()) {
        client.updateCardStatus(CardStatus.STUCK);
    }
    else {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a status first");
        return;
    }
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card status updated successfully");
    refreshStatus();
    }

    /**
    * Sets card status to LOST when the Lost option is selected.
    * Used when the card is reported lost or stolen.
    */
    private void LostActionPerformed(java.awt.event.ActionEvent evt) {
    client.updateCardStatus(CardStatus.LOST);
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to LOST");
    refreshStatus();
    }

    /**
    * Sets card status to STUCK when the Stuck option is selected.
    * Used when the card is retained by an ATM.
    */
     private void StuckActionPerformed(java.awt.event.ActionEvent evt) {
    client.updateCardStatus(CardStatus.STUCK);
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to STUCK");
    refreshStatus();
    }

    /**
    * Blocks the client's card by setting its status to LOST.
    * Used when the card is reported lost or stolen.
    */
    private void blockCardActionPerformed(java.awt.event.ActionEvent evt) {
    client.updateCardStatus(CardStatus.LOST);
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card blocked (LOST)");
    refreshStatus();
    }

    /**
    * Sets card status to INACTIVE when the Inactive option is selected.
    * Updates the UI label to reflect the new status.
    */
    private void InactiveActionPerformed(java.awt.event.ActionEvent evt) {
    client.updateCardStatus(CardStatus.INACTIVE);
    saveIfNeeded();
    javax.swing.JOptionPane.showMessageDialog(this, "Card set to INACTIVE");
    refreshStatus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http:
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new CardManagementFrame().setVisible(true);
    });
    }

    
    private javax.swing.JRadioButton Active;
    private javax.swing.JLabel Cardmanagement;
    private javax.swing.JRadioButton Inactive;
    private javax.swing.JRadioButton Lost;
    private javax.swing.JRadioButton Stuck;
    private javax.swing.JButton blockCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton issueCard;
    private javax.swing.JLabel statusLabel;
    
}
