package gui.customer;

import gui.auth.LoginFrame;
import manager.BankSystem;
import models.account.Account;
import models.user.Client;
import models.user.User;

import javax.swing.JOptionPane;

/**
 *
 * @author Yosef - 255796
 */
public class ClientDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientDashboard.class.getName());

    private User currentUser;
    private Client currentClient;
    private BankSystem bank;

    public ClientDashboard(User user) {
        this(user, null);
    }

    public ClientDashboard(User user, BankSystem bank) {
        initComponents();
        this.currentUser = user;
        this.bank = bank;
        this.currentClient = (user instanceof Client) ? (Client) user : null;

        System.out.println("Logged in as: " + (user != null ? user.getName() : "Guest"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        WithdrawDeposit = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        manageCard = new javax.swing.JButton();
        viewHistory = new javax.swing.JButton();
        PayBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("client Dashboard");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Client Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        WithdrawDeposit.setText("Withdraw/Deposit");
        WithdrawDeposit.addActionListener(this::WithdrawDepositActionPerformed);

        transfer.setText("Transfer");
        transfer.addActionListener(this::transferActionPerformed);

        logout.setText("Logout");
        logout.addActionListener(this::logoutActionPerformed);

        manageCard.setText("Manage Card");
        manageCard.addActionListener(this::manageCardActionPerformed);

        viewHistory.setText("View History");
        viewHistory.addActionListener(this::viewHistoryActionPerformed);

        PayBill.setText("Pay Bill");
        PayBill.addActionListener(this::PayBillActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PayBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WithdrawDeposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(transfer)
                .addGap(18, 18, 18)
                .addComponent(PayBill)
                .addGap(18, 18, 18)
                .addComponent(viewHistory)
                .addGap(18, 18, 18)
                .addComponent(WithdrawDeposit)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(manageCard))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawDepositActionPerformed
        if (currentClient == null || currentClient.getAccounts().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No accounts available", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Account account = currentClient.getAccounts().get(0);
        new TransactionPanel(account, bank).setVisible(true);
    }//GEN-LAST:event_WithdrawDepositActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentClient == null || currentClient.getAccounts().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No accounts available", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Account account = currentClient.getAccounts().get(0);
        new TransferFrame(account, bank).setVisible(true);
    }

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        if (bank != null) {
            bank.saveAllData();
        }
        dispose();
        new LoginFrame(bank).setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void manageCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCardActionPerformed
        if (currentClient == null) {
            JOptionPane.showMessageDialog(this, "No client selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new CardManagementFrame(currentClient, bank).setVisible(true);
    }//GEN-LAST:event_manageCardActionPerformed

    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentClient == null || currentClient.getAccounts().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No accounts available", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Account account = currentClient.getAccounts().get(0);
        new TransactionHistoryFrame(account).setVisible(true);
    }

    private void PayBillActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentClient == null) {
            JOptionPane.showMessageDialog(this, "No client selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new PayBillForm(currentClient, bank).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientDashboard(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PayBill;
    private javax.swing.JButton WithdrawDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageCard;
    private javax.swing.JButton transfer;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables
}
