/*
 */
package gui.customer;

import models.user.Client;

/**
 * Dialog used to pay bills from client account
 * Allows user to select bill type and pay a specified amount
 *
 * @author Yousif Hafez - 258612
 */
public class PayBillForm extends javax.swing.JFrame {
    Client client;
    manager.BankSystem bank;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayBillForm.class.getName());

    public PayBillForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public PayBillForm(Client c) {
        this(c, null);
    }

    public PayBillForm(Client c, manager.BankSystem bank) {
        initComponents();
        this.client = c;
        this.bank = bank;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enter_amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        Pay = new javax.swing.JButton();
        billTypeCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enter_amount.setText("Enter Amount:");

        amountField.addActionListener(this::amountFieldActionPerformed);

        Pay.setText("Pay");
        Pay.addActionListener(this::PayActionPerformed);

        billTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilities", "Subscription", "Credit Card" }));
        billTypeCombo.addActionListener(this::billTypeComboActionPerformed);

        jLabel1.setText("Bill Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Enter_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Pay)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enter_amount)
                    .addComponent(amountField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(billTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Pay)
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Handles bill payment when Pay button is clicked
    */
    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
    try {
        // Read amount
        double amount = Double.parseDouble(amountField.getText());

        // Get selected bill type
        String billType = billTypeCombo.getSelectedItem().toString();

        // Call method
        client.payBill(billType, amount);

        if (bank != null) {
            bank.saveAllData();
        }

        // Success
        javax.swing.JOptionPane.showMessageDialog(this, "Payment successful");

        // Clear field
        amountField.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid number");

    } catch (RuntimeException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_PayActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void billTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billTypeComboActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayBillForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enter_amount;
    private javax.swing.JButton Pay;
    private javax.swing.JTextField amountField;
    private javax.swing.JComboBox<String> billTypeCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
