/*
 */
package gui.customer;
import javax.swing.table.DefaultTableModel;
import models.account.Account;
import models.transaction.Transaction;
/**
 *
 * @author tareq
 */
public class TransactionHistoryFrame extends javax.swing.JFrame {
    private models.account.Account account;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionHistoryFrame.class.getName());

    /**
     * Creates new form TransactionHistoryFrame
     */
    public TransactionHistoryFrame(Account account) {
    initComponents();
    this.account = account;

    setResizable(true);
    setLocationRelativeTo(null);

    loadTable();
}

    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        model.setRowCount(0);

        for (Transaction t : account.getTransactionHistory().getHistory()) {

            if (t.getAccountId().equals(account.getAccountNumber())) {

                model.addRow(new Object[]{
                    t.getTransactionId(),
                    t.getClass().getSimpleName(),
                    t.getAmount(),
                    t.getStatus()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(historyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        try {
            manager.BankSystem bankSystem = new manager.BankSystem();

            bankSystem.loadAllData();

            new gui.auth.LoginFrame(bankSystem).setVisible(true);

        } catch (exceptions.DataLoadException e) {
            System.out.println(e.getUserMessage());

        } catch (Exception e) {
            e.printStackTrace();
        }
    });
}

    
    private javax.swing.JTable historyTable;
    private javax.swing.JScrollPane jScrollPane1;
    
}
