/*
 * Click nbfs:
 * Click nbfs:
 */
package gui.admin;

import gui.auth.RegisterFrame;
import gui.util.Toast;
import manager.BankSystem;
import models.user.Admin;

/**
 * Main admin dashboard window.
 * @author Youssef Adel 258270
 */
public class AdminDashboard extends javax.swing.JFrame {

    private Admin admin;
    private BankSystem bank;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(Admin admin, BankSystem bank) {
        this.admin = admin;
        this.bank = bank;

        initComponents();
        lblWelcome.setText("Welcome, " + admin.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnAddStaff = new javax.swing.JButton();
        btnRemoveStaff = new javax.swing.JButton();
        btnViewStaff = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");

        lblWelcome.setFont(new java.awt.Font("sansserif", 0, 14));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Admin");

        btnAddStaff.setFont(new java.awt.Font("sansserif", 1, 14));
        btnAddStaff.setText("Add Staff");
        btnAddStaff.setPreferredSize(new java.awt.Dimension(150, 40));
        btnAddStaff.addActionListener(this::btnAddStaffActionPerformed);

        btnRemoveStaff.setFont(new java.awt.Font("sansserif", 1, 14));
        btnRemoveStaff.setText("Remove Staff");
        btnRemoveStaff.setPreferredSize(new java.awt.Dimension(150, 40));
        btnRemoveStaff.addActionListener(this::btnRemoveStaffActionPerformed);

        btnViewStaff.setFont(new java.awt.Font("sansserif", 1, 14));
        btnViewStaff.setText("View Staff-list");
        btnViewStaff.setPreferredSize(new java.awt.Dimension(150, 40));
        btnViewStaff.addActionListener(this::btnViewStaffActionPerformed);

        btnReports.setFont(new java.awt.Font("sansserif", 1, 14));
        btnReports.setText("View Reports");
        btnReports.setPreferredSize(new java.awt.Dimension(150, 40));
        btnReports.setBackground(new java.awt.Color(70, 130, 180));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setFocusPainted(false);
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnLogout.setFont(new java.awt.Font("sansserif", 1, 14));
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLogout.setBackground(new java.awt.Color(220, 20, 60));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(btnAddStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(lblWelcome)
                .addGap(30, 30, 30)
                .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnRemoveStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnViewStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {
        new AddStaffMember(bank).setVisible(true);
    }

    private void btnRemoveStaffActionPerformed(java.awt.event.ActionEvent evt) {
        Toast.showInfo(this, "Remove Staff - Coming soon");
    }

    private void btnViewStaffActionPerformed(java.awt.event.ActionEvent evt) {
        new ViewStaffListDialog(bank).setVisible(true);
    }

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {
        new ViewReportsDialog(this).setVisible(true);
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {
        bank.saveAllData();
        admin.logout();
        Toast.showSuccess(this, "Logged out successfully");
        dispose();
        new gui.auth.LoginFrame(bank).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveStaff;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnViewStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
