package gui.admin;

import exceptions.AccountDeletionException;
import manager.BankSystem;
import models.account.Account;
import models.user.Client;

/**
 * Dialog used to delete a client account
 * Allows admin/user to remove account if balance is zero
 *
 * @author Yousif Hafez - 258612
 */
public class DeleteAccountDialog extends javax.swing.JFrame {
    /**
    * The client whose accounts will be managed
    */
    private Client client;
    private BankSystem bank;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteAccountDialog.class.getName());

    /**
     * Creates new form DeleteAccountDialog
     */
    public DeleteAccountDialog() {
        initComponents();
    }

    /**
    * Creates a new DeleteAccountDialog linked to a specific client
    *
    * @param client the client whose account will be deleted
    */
    public DeleteAccountDialog(Client client) {
        this(client, null);
    }

    /**
    * Creates a new DeleteAccountDialog linked to a specific client and bank
    *
    * @param client the client whose account will be deleted
    * @param bank the bank system for saving changes
    */
    public DeleteAccountDialog(Client client, BankSystem bank) {
        initComponents();
        this.client = client;
        this.bank = bank;
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountIdField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Account ID:");

        accountIdField.addActionListener(this::accountIdFieldActionPerformed);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountIdFieldActionPerformed

    /**
    * Handles delete button click
    * Deletes account only if balance is zero
    */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (client == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No client selected");
            return;
        }

        String accountId = accountIdField.getText().trim();
        if (accountId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an account ID");
            return;
        }

        try {
            Account target = null;
            for (Account acc : client.getAccounts()) {
                if (acc.getAccountNumber().equals(accountId)) {
                    target = acc;
                    break;
                }
            }

            if (target == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Account not found");
                return;
            }

            if (target.getBalance() > 0) {
                throw new AccountDeletionException();
            }

            client.getAccounts().remove(target);

            if (bank != null) {
                bank.saveAllData();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Account deleted successfully");
            accountIdField.setText("");

        } catch (AccountDeletionException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteAccountDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountIdField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
