package gui.admin;

/*
 * Click nbfs:
 * Click nbfs:
 */
import javax.swing.table.DefaultTableModel;
import manager.BankSystem;
import models.user.Admin;
import models.user.User;

/**
 * Displays all staff members in a table.
 * @author Yousef Mohiey - 248679
 */

public class ViewStaffListDialog extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewStaffListDialog.class.getName());

    private BankSystem bank;

    /**
     * Creates new form ViewStaffListDialog
     */
    public ViewStaffListDialog(BankSystem bank) {
        initComponents();
        this.bank = bank;
        showStaff();
    }
    private void showStaff() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (User u : bank.getUsers()) {
            if (u instanceof Admin) {
                Admin a = (Admin) u;
                model.addRow(new Object[]{a.getName(),a.getJobTitle() ,a.getEmail(),a.getPhoneNumber()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bRefresh = new javax.swing.JButton();
        bClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 20));
        jLabel1.setText("Staff Members");

        jTable1.setFont(new java.awt.Font("sansserif", 1, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Job title", "Email", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(this::bRefreshActionPerformed);

        bClose.setText("Close");
        bClose.addActionListener(this::bCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bRefresh)
                        .addGap(318, 318, 318)
                        .addComponent(bClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRefresh)
                    .addComponent(bClose))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {
        showStaff();
    }

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
