/*
 * Click nbfs:
 * Click nbfs:
 */
package gui.admin;

import gui.util.Toast;
import manager.BankSystem;
import models.account.Account;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * Dialog to view all customer accounts.
 * @author AbdelrahmanMazen 251979
 */
public class ViewAccountsDialog extends javax.swing.JDialog {

    private DefaultTableModel tableModel;
    private BankSystem bank;

    /**
     * Creates new form ViewAccountsDialog
     */
    public ViewAccountsDialog(java.awt.Frame parent, boolean modal, BankSystem bank) {
        super(parent, modal);
        this.bank = bank;
        initComponents();
        loadAccounts();
    }

    public ViewAccountsDialog(java.awt.Frame parent, BankSystem bank) {
        this(parent, true, bank);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setTitle("View All Accounts");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Customer Accounts");

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Type", "Balance", "Owner", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAccounts);

        btnRefresh.setFont(new java.awt.Font("sansserif", 1, 13));
        btnRefresh.setText("Refresh");
        btnRefresh.setPreferredSize(new java.awt.Dimension(100, 35));
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnClose.setFont(new java.awt.Font("sansserif", 1, 13));
        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 35));
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
        loadAccounts();
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAccountsDialog dialog = new ViewAccountsDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccounts;
    // End of variables declaration//GEN-END:variables

    private void loadAccounts() {
        tableModel = (DefaultTableModel) tblAccounts.getModel();
        tableModel.setRowCount(0);

        if (bank == null) {
            Toast.showInfo(this, "No bank system connected.");
            return;
        }

        try {
            ArrayList<Account> accounts = bank.getAllAccounts();

            if (accounts.isEmpty()) {
                Toast.showInfo(this, "No accounts found.");
                return;
            }

            for (Account acc : accounts) {
                String accNum = acc.getAccountNumber();
                String type = acc.getClass().getSimpleName();
                String balance = String.format("$%.2f", acc.getBalance());
                String owner = acc.getOwner() != null ? acc.getOwner().getName() : "Unknown";
                String status = "Active";

                tableModel.addRow(new Object[]{accNum, type, balance, owner, status});
            }

            Toast.showSuccess(this, "Loaded " + tableModel.getRowCount() + " account(s)");

        } catch (Exception e) {
            Toast.showError(this, "Failed to load accounts: " + e.getMessage());
        }
    }
}
