/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.auth;

import javax.swing.JOptionPane;
import exceptions.InvalidLoginException;
import gui.admin.AdminDashboard;
import gui.customer.ClientDashboard;
import manager.BankSystem;
import models.user.User;
import models.user.Admin;



/**
 * LoginFrame - Main login GUI for Phase 2
 * @author Yousef Mohiey - 248679
 * @since Phase 2
 */
public class LoginFrame extends javax.swing.JFrame {
    
// Track Login attempts
    
    private BankSystem bank;
    private int failedAttempts = 0;
    private static final int MAX_ATTEMPTS = 3;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());


    public LoginFrame(BankSystem bank) {
        this.bank = bank;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jpassowrd = new javax.swing.JPasswordField();
        bexit = new javax.swing.JButton();
        blogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("Online Banking Login");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel3.setText("Passowrd");

        jtuser.addActionListener(this::jtuserActionPerformed);

        jpassowrd.addActionListener(this::jpassowrdActionPerformed);

        bexit.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        bexit.setText("Exit");
        bexit.addActionListener(this::bexitActionPerformed);

        blogin.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        blogin.setText("Login");
        blogin.addActionListener(this::bloginActionPerformed);

        jLabel4.setText("Attempts left: 3");

        ShowPassword.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        ShowPassword.setText("Show Passowrd");
        ShowPassword.addActionListener(this::ShowPasswordActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShowPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpassowrd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtuser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpassowrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPassword)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed

        bloginActionPerformed(evt);
        
    }//GEN-LAST:event_jtuserActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?", "Confirm Exit",JOptionPane.YES_NO_OPTION );
        if (confirm == JOptionPane.YES_OPTION) 
        {
            System.exit(0);
        }
    }//GEN-LAST:event_bexitActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        String username = jtuser.getText().trim();
        char[] passwordChars = jpassowrd.getPassword();
        String password = new String(passwordChars);
        
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your username", "Input Required", JOptionPane.WARNING_MESSAGE);
            jtuser.requestFocus();
            return;
        }
        
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password", "Input Required", JOptionPane.WARNING_MESSAGE);
            jpassowrd.requestFocus();
            return;
        }
        
       try 
       {
           
        if (bank.login(username, password)) {
            failedAttempts = 0;
            User user = bank.getCurrentUser(); 
            
            JOptionPane.showMessageDialog(this, "Login successful. Welcome, " + user.getName(), "Success", JOptionPane.INFORMATION_MESSAGE);
            
            //  Route to correct dashboard using real object
            if (user instanceof Admin) {
                new AdminDashboard((Admin) user, bank).setVisible(true);
            } else {
                new ClientDashboard(user).setVisible(true);
            }
            dispose();
        } else {
            throw new InvalidLoginException("Invalid username or password");
        }
    } catch (InvalidLoginException e) {
        failedAttempts++;
        if (failedAttempts >= MAX_ATTEMPTS) {
            JOptionPane.showMessageDialog(this, e.getMessage() + "\nToo many failed attempts. Exiting.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else {
            int left = MAX_ATTEMPTS - failedAttempts;
            JOptionPane.showMessageDialog(this, e.getMessage() + "\nAttempts left: " + left, "Login Failed", JOptionPane.WARNING_MESSAGE);
            jLabel4.setText("Attempts left: " + left);
            jpassowrd.setText("");
            jpassowrd.requestFocus();
        }
    } finally {
        java.util.Arrays.fill(jpassowrd.getPassword(), ' ');
    }
        
    }//GEN-LAST:event_bloginActionPerformed

       
    private void jpassowrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassowrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassowrdActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
          if (ShowPassword.isSelected()) {
        // Show password as plain text
        jpassowrd.setEchoChar((char)0);
    } else {
        // Hide password with dots
        jpassowrd.setEchoChar('*');
    }
    }//GEN-LAST:event_ShowPasswordActionPerformed
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JButton bexit;
    private javax.swing.JButton blogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jpassowrd;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables
}
